import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

// Translation data
const translations = {
    id: {
        // Navigation
        'nav.home': 'Beranda',
        'nav.portfolio': 'Portfolio',
        'nav.blog': 'Blog',
        'nav.clients': 'Klien',
        'nav.careers': 'Karir',
        'nav.contact': 'Kontak',

        // Home Page
        'home.hero.title': 'Selamat Datang di NAVA DHANARAMA INDONESIA',
        'home.hero.subtitle': 'Membangun Masa Depan Digital dengan Inovasi dan Teknologi Terdepan',
        'home.hero.description': 'Kami adalah tim ahli teknologi yang berdedikasi untuk memberikan solusi digital terbaik bagi bisnis Anda. Dengan pengalaman bertahun-tahun dan komitmen terhadap kualitas, kami siap membantu mewujudkan visi digital perusahaan Anda.',
        'home.hero.cta': 'Mulai Proyek Anda',
        'home.hero.portfolio': 'Lihat Portfolio',

        'home.services.title': 'Layanan Kami',
        'home.services.subtitle': 'Solusi teknologi komprehensif untuk kebutuhan bisnis modern',
        'home.services.web.title': 'Pengembangan Web',
        'home.services.web.desc': 'Website dan aplikasi web modern dengan teknologi terkini',
        'home.services.mobile.title': 'Aplikasi Mobile',
        'home.services.mobile.desc': 'Aplikasi mobile native dan cross-platform untuk iOS & Android',
        'home.services.system.title': 'Sistem Informasi',
        'home.services.system.desc': 'Sistem manajemen dan enterprise terintegrasi',
        'home.services.consulting.title': 'Konsultasi IT',
        'home.services.consulting.desc': 'Strategi dan konsultasi teknologi untuk transformasi digital',

        'home.portfolio.title': 'Portfolio Terbaru',
        'home.portfolio.subtitle': 'Lihat beberapa proyek terbaik yang telah kami kerjakan',
        'home.portfolio.viewAll': 'Lihat Semua Portfolio',

        'home.blog.title': 'Artikel Terbaru',
        'home.blog.subtitle': 'Insights dan tips teknologi dari tim ahli kami',
        'home.blog.viewAll': 'Lihat Semua Artikel',
        'home.blog.readMore': 'Baca Selengkapnya',

        'home.clients.title': 'Dipercaya Oleh',
        'home.clients.subtitle': 'Perusahaan-perusahaan terkemuka yang mempercayai layanan kami',

        'home.cta.title': 'Siap Memulai Proyek Anda?',
        'home.cta.subtitle': 'Mari diskusikan bagaimana kami dapat membantu mengembangkan bisnis Anda dengan solusi teknologi yang tepat.',
        'home.cta.contact': 'Hubungi Kami',
        'home.cta.consultation': 'Konsultasi Gratis',

        // Portfolio
        'portfolio.title': 'Portfolio Kami',
        'portfolio.subtitle': 'Koleksi proyek terbaik yang menunjukkan keahlian dan dedikasi tim kami',
        'portfolio.filter.all': 'Semua',
        'portfolio.filter.web': 'Website',
        'portfolio.filter.mobile': 'Mobile App',
        'portfolio.filter.system': 'Sistem',
        'portfolio.viewProject': 'Lihat Proyek',
        'portfolio.techStack': 'Tech Stack',
        'portfolio.liveDemo': 'Demo Langsung',
        'portfolio.sourceCode': 'Source Code',
        'portfolio.relatedProjects': 'Proyek Terkait',

        // Blog
        'blog.title': 'Blog & Artikel',
        'blog.subtitle': 'Insights, tips, dan tren teknologi terbaru dari tim ahli kami',
        'blog.search': 'Cari artikel...',
        'blog.categories': 'Kategori',
        'blog.allCategories': 'Semua Kategori',
        'blog.readMore': 'Baca Selengkapnya',
        'blog.readingTime': 'menit baca',
        'blog.shareArticle': 'Bagikan artikel ini',
        'blog.relatedArticles': 'Artikel Terkait',
        'blog.backToBlog': 'Kembali ke Blog',
        'blog.author': 'Penulis',
        'blog.publishedOn': 'Dipublikasikan pada',
        'blog.tags': 'Tags',
        'blog.newsletter.title': 'Tetap Update',
        'blog.newsletter.subtitle': 'Dapatkan artikel dan insights terbaru langsung ke inbox Anda',
        'blog.newsletter.cta': 'Baca Artikel Lainnya',
        'blog.newsletter.subscribe': 'Berlangganan Newsletter',

        // Clients
        'clients.title': 'Klien Terpercaya Kami',
        'clients.subtitle': 'Kami bangga bekerja sama dengan perusahaan-perusahaan luar biasa yang mempercayai kami untuk memberikan solusi digital yang inovatif.',
        'clients.stats.clients': 'Klien Bahagia',
        'clients.stats.projects': 'Proyek Selesai',
        'clients.stats.satisfaction': 'Kepuasan Klien',
        'clients.stats.experience': 'Tahun Pengalaman',
        'clients.services.title': 'Layanan yang Kami Berikan kepada Klien',
        'clients.services.subtitle': 'Solusi digital komprehensif yang disesuaikan dengan kebutuhan bisnis yang beragam',
        'clients.cta.title': 'Siap Bergabung dengan Keluarga Klien Kami?',
        'clients.cta.subtitle': 'Mari diskusikan bagaimana kami dapat membantu mentransformasi bisnis Anda dengan solusi inovatif kami.',
        'clients.cta.start': 'Mulai Proyek Anda',
        'clients.cta.viewWork': 'Lihat Karya Kami',
        'clients.industry': 'Industri',
        'clients.website': 'Kunjungi Website',
        'clients.projects': 'Proyek',
        'clients.since': 'Partner sejak',
        'clients.noClients': 'Tidak ada klien untuk ditampilkan',
        'clients.noClientsDesc': 'Kami selalu mencari kemitraan dan kolaborasi baru.',
        'clients.partnerWithUs': 'Bermitra dengan Kami',

        // Careers
        'careers.title': 'Bergabunglah dengan Tim Kami',
        'careers.subtitle': 'Jelajahi peluang karir yang menarik dan menjadi bagian dari tim inovatif kami yang membangun masa depan solusi digital.',
        'careers.benefits.title': 'Mengapa Bekerja dengan Kami?',
        'careers.benefits.subtitle': 'Bergabunglah dengan tim yang menghargai inovasi, pertumbuhan, dan keseimbangan kerja-hidup',
        'careers.benefits.innovation': 'Proyek Inovatif',
        'careers.benefits.innovation.desc': 'Bekerja pada proyek mutakhir menggunakan teknologi dan framework terbaru',
        'careers.benefits.learning': 'Pembelajaran Berkelanjutan',
        'careers.benefits.learning.desc': 'Akses ke kursus, konferensi, dan program sertifikasi untuk meningkatkan keahlian Anda',
        'careers.benefits.flexibility': 'Fleksibilitas Remote',
        'careers.benefits.flexibility.desc': 'Pengaturan kerja fleksibel dengan opsi remote dan hybrid yang tersedia',
        'careers.benefits.team': 'Tim Kolaboratif',
        'careers.benefits.team.desc': 'Bekerja dengan profesional yang bersemangat dalam lingkungan yang mendukung dan inklusif',
        'careers.benefits.compensation': 'Benefit Kompetitif',
        'careers.benefits.compensation.desc': 'Paket gaji menarik dengan asuransi kesehatan dan bonus kinerja',
        'careers.benefits.growth': 'Pertumbuhan Karir',
        'careers.benefits.growth.desc': 'Jalur progres karir yang jelas dengan mentoring dan peluang kepemimpinan',
        'careers.cta.title': 'Siap Bergabung dengan Tim Kami?',
        'careers.cta.subtitle': 'Tidak melihat posisi yang cocok? Kirimkan CV Anda dan kami akan menghubungi Anda untuk peluang di masa depan.',
        'careers.cta.apply': 'Kirim Lamaran Anda',
        'careers.viewDetails': 'Lihat Detail',
        'careers.applyNow': 'Lamar Sekarang',
        'careers.location': 'Lokasi',
        'careers.salary': 'Gaji',
        'careers.department': 'Departemen',
        'careers.requirements': 'Persyaratan Utama',
        'careers.type.fullTime': 'Penuh Waktu',
        'careers.type.partTime': 'Paruh Waktu',
        'careers.type.contract': 'Kontrak',
        'careers.type.remote': 'Remote',
        'careers.type.competitive': 'Kompetitif',
        'careers.noPositions': 'Tidak ada posisi terbuka',
        'careers.noPositionsDesc': 'Saat ini tidak ada peluang karir yang terbuka. Periksa kembali nanti!',
        'careers.sendCV': 'Kirim CV Kami',
        'careers.backToCareers': 'Kembali ke Karir',
        'careers.jobDescription': 'Deskripsi Pekerjaan',
        'careers.responsibilities': 'Tanggung Jawab',
        'careers.whatWeOffer': 'Yang Kami Tawarkan',
        'careers.interested': 'Tertarik dengan posisi ini?',
        'careers.interestedDesc': 'Kirimkan lamaran Anda dan kami akan menghubungi Anda secepatnya.',
        'careers.applyPosition': 'Lamar untuk Posisi Ini',
        'careers.viewAllCareers': 'Lihat Semua Karir',
        'careers.shareJob': 'Bagikan pekerjaan ini',
        'careers.quickInfo': 'Info Cepat',
        'careers.experienceLevel': 'Tingkat Pengalaman',
        'careers.posted': 'Dipublikasikan',
        'careers.readyToApply': 'Siap Melamar?',
        'careers.readyToApplyDesc': 'Ambil langkah selanjutnya dalam perjalanan karir Anda bersama kami.',
        'careers.otherOpportunities': 'Peluang Lainnya',
        'careers.otherOpportunitiesDesc': 'Jelajahi peluang karir menarik lainnya di NAVA DHANARAMA INDONESIA',

        // Contact
        'contact.title': 'Hubungi Kami',
        'contact.subtitle': 'Siap memulai proyek atau ingin bertanya? Tim kami siap membantu Anda.',
        'contact.getInTouch': 'Mari Berdiskusi',
        'contact.info.address': 'Alamat',
        'contact.info.phone': 'Telepon',
        'contact.info.email': 'Email',
        'contact.info.hours': 'Jam Kerja',
        'contact.info.hoursValue': 'Senin - Jumat: 09:00 - 17:00',
        'contact.form.name': 'Nama Lengkap',
        'contact.form.email': 'Alamat Email',
        'contact.form.phone': 'Nomor Telepon',
        'contact.form.company': 'Nama Perusahaan',
        'contact.form.position': 'Posisi/Jabatan',
        'contact.form.projectType': 'Jenis Proyek',
        'contact.form.budget': 'Budget',
        'contact.form.message': 'Pesan',
        'contact.form.cv': 'Upload CV (Opsional)',
        'contact.form.submit': 'Kirim Pesan',
        'contact.form.sending': 'Mengirim...',
        'contact.form.namePlaceholder': 'Masukkan nama lengkap Anda',
        'contact.form.emailPlaceholder': 'nama@email.com',
        'contact.form.phonePlaceholder': '+62 812 3456 7890',
        'contact.form.companyPlaceholder': 'Nama perusahaan Anda',
        'contact.form.positionPlaceholder': 'Posisi/jabatan Anda',
        'contact.form.messagePlaceholder': 'Ceritakan tentang proyek atau kebutuhan Anda...',
        'contact.form.projectTypes.web': 'Website/Web App',
        'contact.form.projectTypes.mobile': 'Mobile App',
        'contact.form.projectTypes.system': 'Sistem Informasi',
        'contact.form.projectTypes.consulting': 'Konsultasi IT',
        'contact.form.projectTypes.other': 'Lainnya',
        'contact.form.budgets.small': '< 50 Juta',
        'contact.form.budgets.medium': '50 - 200 Juta',
        'contact.form.budgets.large': '200 - 500 Juta',
        'contact.form.budgets.enterprise': '> 500 Juta',
        'contact.form.budgets.discuss': 'Mari Diskusikan',
        'contact.why.title': 'Mengapa Memilih Kami?',
        'contact.why.experience': 'Berpengalaman',
        'contact.why.experienceDesc': 'Tim ahli dengan pengalaman bertahun-tahun',
        'contact.why.quality': 'Kualitas Terbaik',
        'contact.why.qualityDesc': 'Standar kualitas tinggi dalam setiap proyek',
        'contact.why.support': 'Support 24/7',
        'contact.why.supportDesc': 'Dukungan teknis dan konsultasi berkelanjutan',
        'contact.why.onTime': 'Tepat Waktu',
        'contact.why.onTimeDesc': 'Komitmen untuk menyelesaikan proyek sesuai jadwal',
        'contact.cta.title': 'Siap Memulai?',
        'contact.cta.subtitle': 'Mari wujudkan ide digital Anda bersama tim ahli kami.',
        'contact.cta.call': 'Hubungi Sekarang',
        'contact.cta.whatsapp': 'Chat WhatsApp',

        // Common
        'common.loading': 'Memuat...',
        'common.readMore': 'Baca Selengkapnya',
        'common.viewAll': 'Lihat Semua',
        'common.backToTop': 'Kembali ke Atas',
        'common.search': 'Cari',
        'common.filter': 'Filter',
        'common.sort': 'Urutkan',
        'common.date': 'Tanggal',
        'common.author': 'Penulis',
        'common.category': 'Kategori',
        'common.tags': 'Tags',
        'common.share': 'Bagikan',
        'common.close': 'Tutup',
        'common.open': 'Buka',
        'common.menu': 'Menu',
        'common.more': 'Lainnya',
        'common.less': 'Lebih Sedikit',
        'common.showMore': 'Tampilkan Lebih Banyak',
        'common.showLess': 'Tampilkan Lebih Sedikit',
        'common.noResults': 'Tidak ada hasil ditemukan',
        'common.tryAgain': 'Coba Lagi',
        'common.error': 'Terjadi kesalahan',
        'common.success': 'Berhasil',
        'common.warning': 'Peringatan',
        'common.info': 'Informasi',

        // Footer
        'footer.company': 'Perusahaan',
        'footer.services': 'Layanan',
        'footer.resources': 'Sumber Daya',
        'footer.contact': 'Kontak',
        'footer.followUs': 'Ikuti Kami',
        'footer.copyright': 'Hak Cipta',
        'footer.allRightsReserved': 'Semua hak dilindungi.',
        'footer.about': 'Tentang Kami',
        'footer.team': 'Tim',
        'footer.careers': 'Karir',
        'footer.news': 'Berita',
        'footer.webDev': 'Pengembangan Web',
        'footer.mobileDev': 'Pengembangan Mobile',
        'footer.systemDev': 'Sistem Informasi',
        'footer.consulting': 'Konsultasi IT',
        'footer.blog': 'Blog',
        'footer.documentation': 'Dokumentasi',
        'footer.support': 'Dukungan',
        'footer.privacy': 'Kebijakan Privasi',
        'footer.terms': 'Syarat & Ketentuan',
    },
    en: {
        // Navigation
        'nav.home': 'Home',
        'nav.portfolio': 'Portfolio',
        'nav.blog': 'Blog',
        'nav.clients': 'Clients',
        'nav.careers': 'Careers',
        'nav.contact': 'Contact',

        // Home Page
        'home.hero.title': 'Welcome to NAVA DHANARAMA INDONESIA',
        'home.hero.subtitle': 'Building Digital Future with Innovation and Leading Technology',
        'home.hero.description': 'We are a dedicated team of technology experts committed to providing the best digital solutions for your business. With years of experience and commitment to quality, we are ready to help realize your company\'s digital vision.',
        'home.hero.cta': 'Start Your Project',
        'home.hero.portfolio': 'View Portfolio',

        'home.services.title': 'Our Services',
        'home.services.subtitle': 'Comprehensive technology solutions for modern business needs',
        'home.services.web.title': 'Web Development',
        'home.services.web.desc': 'Modern websites and web applications with cutting-edge technology',
        'home.services.mobile.title': 'Mobile Applications',
        'home.services.mobile.desc': 'Native and cross-platform mobile apps for iOS & Android',
        'home.services.system.title': 'Information Systems',
        'home.services.system.desc': 'Integrated management and enterprise systems',
        'home.services.consulting.title': 'IT Consulting',
        'home.services.consulting.desc': 'Technology strategy and consulting for digital transformation',

        'home.portfolio.title': 'Latest Portfolio',
        'home.portfolio.subtitle': 'See some of the best projects we have worked on',
        'home.portfolio.viewAll': 'View All Portfolio',

        'home.blog.title': 'Latest Articles',
        'home.blog.subtitle': 'Technology insights and tips from our expert team',
        'home.blog.viewAll': 'View All Articles',
        'home.blog.readMore': 'Read More',

        'home.clients.title': 'Trusted By',
        'home.clients.subtitle': 'Leading companies that trust our services',

        'home.cta.title': 'Ready to Start Your Project?',
        'home.cta.subtitle': 'Let\'s discuss how we can help grow your business with the right technology solutions.',
        'home.cta.contact': 'Contact Us',
        'home.cta.consultation': 'Free Consultation',

        // Portfolio
        'portfolio.title': 'Our Portfolio',
        'portfolio.subtitle': 'A collection of our best projects showcasing our team\'s expertise and dedication',
        'portfolio.filter.all': 'All',
        'portfolio.filter.web': 'Website',
        'portfolio.filter.mobile': 'Mobile App',
        'portfolio.filter.system': 'System',
        'portfolio.viewProject': 'View Project',
        'portfolio.techStack': 'Tech Stack',
        'portfolio.liveDemo': 'Live Demo',
        'portfolio.sourceCode': 'Source Code',
        'portfolio.relatedProjects': 'Related Projects',

        // Blog
        'blog.title': 'Blog & Articles',
        'blog.subtitle': 'Latest technology insights, tips, and trends from our expert team',
        'blog.search': 'Search articles...',
        'blog.categories': 'Categories',
        'blog.allCategories': 'All Categories',
        'blog.readMore': 'Read More',
        'blog.readingTime': 'min read',
        'blog.shareArticle': 'Share this article',
        'blog.relatedArticles': 'Related Articles',
        'blog.backToBlog': 'Back to Blog',
        'blog.author': 'Author',
        'blog.publishedOn': 'Published on',
        'blog.tags': 'Tags',
        'blog.newsletter.title': 'Stay Updated',
        'blog.newsletter.subtitle': 'Get the latest articles and insights delivered to your inbox',
        'blog.newsletter.cta': 'Read More Articles',
        'blog.newsletter.subscribe': 'Subscribe to Newsletter',

        // Clients
        'clients.title': 'Our Trusted Clients',
        'clients.subtitle': 'We\'re proud to work with amazing companies and organizations who trust us to deliver exceptional digital solutions and innovative technologies.',
        'clients.stats.clients': 'Happy Clients',
        'clients.stats.projects': 'Projects Completed',
        'clients.stats.satisfaction': 'Client Satisfaction',
        'clients.stats.experience': 'Years Experience',
        'clients.services.title': 'Services We Provide to Our Clients',
        'clients.services.subtitle': 'Comprehensive digital solutions tailored to meet diverse business needs',
        'clients.cta.title': 'Ready to Join Our Client Family?',
        'clients.cta.subtitle': 'Let\'s discuss how we can help transform your business with our innovative solutions.',
        'clients.cta.start': 'Start Your Project',
        'clients.cta.viewWork': 'View Our Work',
        'clients.industry': 'Industry',
        'clients.website': 'Visit Website',
        'clients.projects': 'Projects',
        'clients.since': 'Partner since',
        'clients.noClients': 'No clients to display',
        'clients.noClientsDesc': 'We\'re always looking for new partnerships and collaborations.',
        'clients.partnerWithUs': 'Partner With Us',

        // Careers
        'careers.title': 'Join Our Team',
        'careers.subtitle': 'Explore exciting career opportunities and become part of our innovative team building the future of digital solutions.',
        'careers.benefits.title': 'Why Work With Us?',
        'careers.benefits.subtitle': 'Join a team that values innovation, growth, and work-life balance',
        'careers.benefits.innovation': 'Innovative Projects',
        'careers.benefits.innovation.desc': 'Work on cutting-edge projects using the latest technologies and frameworks',
        'careers.benefits.learning': 'Continuous Learning',
        'careers.benefits.learning.desc': 'Access to courses, conferences, and certification programs to enhance your skills',
        'careers.benefits.flexibility': 'Remote Flexibility',
        'careers.benefits.flexibility.desc': 'Flexible working arrangements with remote and hybrid options available',
        'careers.benefits.team': 'Collaborative Team',
        'careers.benefits.team.desc': 'Work with passionate professionals in a supportive and inclusive environment',
        'careers.benefits.compensation': 'Competitive Benefits',
        'careers.benefits.compensation.desc': 'Attractive salary packages with health insurance and performance bonuses',
        'careers.benefits.growth': 'Career Growth',
        'careers.benefits.growth.desc': 'Clear career progression paths with mentorship and leadership opportunities',
        'careers.cta.title': 'Ready to Join Our Team?',
        'careers.cta.subtitle': 'Don\'t see a position that fits? Send us your CV and we\'ll keep you in mind for future opportunities.',
        'careers.cta.apply': 'Send Your Application',
        'careers.viewDetails': 'View Details',
        'careers.applyNow': 'Apply Now',
        'careers.location': 'Location',
        'careers.salary': 'Salary',
        'careers.department': 'Department',
        'careers.requirements': 'Key Requirements',
        'careers.type.fullTime': 'Full Time',
        'careers.type.partTime': 'Part Time',
        'careers.type.contract': 'Contract',
        'careers.type.remote': 'Remote',
        'careers.type.competitive': 'Competitive',
        'careers.noPositions': 'No open positions',
        'careers.noPositionsDesc': 'There are currently no open career opportunities. Check back later!',
        'careers.sendCV': 'Send Us Your CV',
        'careers.backToCareers': 'Back to Careers',
        'careers.jobDescription': 'Job Description',
        'careers.responsibilities': 'Responsibilities',
        'careers.whatWeOffer': 'What We Offer',
        'careers.interested': 'Interested in this position?',
        'careers.interestedDesc': 'Send us your application and we\'ll get back to you as soon as possible.',
        'careers.applyPosition': 'Apply for This Position',
        'careers.viewAllCareers': 'View All Careers',
        'careers.shareJob': 'Share this job',
        'careers.quickInfo': 'Quick Info',
        'careers.experienceLevel': 'Experience Level',
        'careers.posted': 'Posted',
        'careers.readyToApply': 'Ready to Apply?',
        'careers.readyToApplyDesc': 'Take the next step in your career journey with us.',
        'careers.otherOpportunities': 'Other Opportunities',
        'careers.otherOpportunitiesDesc': 'Explore other exciting career opportunities at NAVA DHANARAMA INDONESIA',

        // Contact
        'contact.title': 'Contact Us',
        'contact.subtitle': 'Ready to start a project or have questions? Our team is here to help you.',
        'contact.getInTouch': 'Get In Touch',
        'contact.info.address': 'Address',
        'contact.info.phone': 'Phone',
        'contact.info.email': 'Email',
        'contact.info.hours': 'Working Hours',
        'contact.info.hoursValue': 'Monday - Friday: 09:00 - 17:00',
        'contact.form.name': 'Full Name',
        'contact.form.email': 'Email Address',
        'contact.form.phone': 'Phone Number',
        'contact.form.company': 'Company Name',
        'contact.form.position': 'Position/Title',
        'contact.form.projectType': 'Project Type',
        'contact.form.budget': 'Budget',
        'contact.form.message': 'Message',
        'contact.form.cv': 'Upload CV (Optional)',
        'contact.form.submit': 'Send Message',
        'contact.form.sending': 'Sending...',
        'contact.form.namePlaceholder': 'Enter your full name',
        'contact.form.emailPlaceholder': 'name@email.com',
        'contact.form.phonePlaceholder': '+62 812 3456 7890',
        'contact.form.companyPlaceholder': 'Your company name',
        'contact.form.positionPlaceholder': 'Your position/title',
        'contact.form.messagePlaceholder': 'Tell us about your project or needs...',
        'contact.form.projectTypes.web': 'Website/Web App',
        'contact.form.projectTypes.mobile': 'Mobile App',
        'contact.form.projectTypes.system': 'Information System',
        'contact.form.projectTypes.consulting': 'IT Consulting',
        'contact.form.projectTypes.other': 'Other',
        'contact.form.budgets.small': '< 50 Million',
        'contact.form.budgets.medium': '50 - 200 Million',
        'contact.form.budgets.large': '200 - 500 Million',
        'contact.form.budgets.enterprise': '> 500 Million',
        'contact.form.budgets.discuss': 'Let\'s Discuss',
        'contact.why.title': 'Why Choose Us?',
        'contact.why.experience': 'Experienced',
        'contact.why.experienceDesc': 'Expert team with years of experience',
        'contact.why.quality': 'Best Quality',
        'contact.why.qualityDesc': 'High quality standards in every project',
        'contact.why.support': '24/7 Support',
        'contact.why.supportDesc': 'Continuous technical support and consultation',
        'contact.why.onTime': 'On Time',
        'contact.why.onTimeDesc': 'Commitment to complete projects on schedule',
        'contact.cta.title': 'Ready to Get Started?',
        'contact.cta.subtitle': 'Let\'s bring your digital ideas to life with our expert team.',
        'contact.cta.call': 'Call Now',
        'contact.cta.whatsapp': 'WhatsApp Chat',

        // Common
        'common.loading': 'Loading...',
        'common.readMore': 'Read More',
        'common.viewAll': 'View All',
        'common.backToTop': 'Back to Top',
        'common.search': 'Search',
        'common.filter': 'Filter',
        'common.sort': 'Sort',
        'common.date': 'Date',
        'common.author': 'Author',
        'common.category': 'Category',
        'common.tags': 'Tags',
        'common.share': 'Share',
        'common.close': 'Close',
        'common.open': 'Open',
        'common.menu': 'Menu',
        'common.more': 'More',
        'common.less': 'Less',
        'common.showMore': 'Show More',
        'common.showLess': 'Show Less',
        'common.noResults': 'No results found',
        'common.tryAgain': 'Try Again',
        'common.error': 'An error occurred',
        'common.success': 'Success',
        'common.warning': 'Warning',
        'common.info': 'Information',

        // Footer
        'footer.company': 'Company',
        'footer.services': 'Services',
        'footer.resources': 'Resources',
        'footer.contact': 'Contact',
        'footer.followUs': 'Follow Us',
        'footer.copyright': 'Copyright',
        'footer.allRightsReserved': 'All rights reserved.',
        'footer.about': 'About Us',
        'footer.team': 'Team',
        'footer.careers': 'Careers',
        'footer.news': 'News',
        'footer.webDev': 'Web Development',
        'footer.mobileDev': 'Mobile Development',
        'footer.systemDev': 'Information Systems',
        'footer.consulting': 'IT Consulting',
        'footer.blog': 'Blog',
        'footer.documentation': 'Documentation',
        'footer.support': 'Support',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms & Conditions',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        // Get language from localStorage or default to 'id'
        return localStorage.getItem('language') || 'id';
    });

    useEffect(() => {
        // Save language preference to localStorage
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key, defaultValue = key) => {
        return translations[language]?.[key] || defaultValue;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'id' ? 'en' : 'id');
    };

    const value = {
        language,
        setLanguage,
        t,
        toggleLanguage,
        isIndonesian: language === 'id',
        isEnglish: language === 'en'
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};
